# Generated by Django 2.1.2 on 2018-10-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday_message', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('venue', models.CharField(max_length=255)),
                ('refreshment', models.CharField(choices=[('tea_biscuits', 'Tea & Biscuts'), ('finger_lunch', 'Finger Lunch'), ('sit_down', 'Sit Down Lunch')], max_length=255)),
                ('scheduler_name', models.CharField(max_length=255)),
                ('scheduler_email', models.EmailField(max_length=255)),
                ('scheduler_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_name', models.CharField(max_length=255)),
                ('rsvp_email', models.EmailField(max_length=255)),
                ('rsvp_number', models.CharField(max_length=10)),
                ('having_refreshments', models.BooleanField()),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birthday.Birthday')),
            ],
        ),
    ]
